# This is a development compose.yml. Use the one in examples/compose.yml to bootstrap a template for your project
services:
  dlditool:
    image: aleixmt/dlditool:latest
    container_name: dlditool
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./input:/input
    entrypoint: sh -c "dlditool /usr/bin/mpcf.dldi /input/nds.nds"



